### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by chashmeetsingh** [chashmeetsingh/Airbnb-Clone#2]
Update readme to include the purpose of the app.

**Comment by yasirunilan** [comment]
Can I work on this?

**Comment by chashmeetsingh** [comment]
sure @yasirunilan

**Comment by yasirunilan** [comment]
what sort of things it should include?

**Comment by chashmeetsingh** [comment]
Overview of what the app does?

**Comment by hari-sikchi** [comment]
Am on it

**Comment by kartik95** [comment]
Is this issue resolved? If not, can you give me an overview of the application? @chashmeetsingh

**Comment by chashmeetsingh** [comment]
not yet resolved, you can work on it. its basically airbnb for pets @kartik95

**Comment by kartik95** [comment]
Oh. Nice idea! :D
Will start with it! Thanks.
